### ISSUE TITLE
Error with first two test

### ISSUE THREAD

**Issue by Enoch2k2** [learn-co-curriculum/javascript-arrays-lab#13]
A student was looking in the index-test.js and noticed there was two test that automatically passes (the test that checks if you create the kittens array). He was unsure how to define the array. He actually had this code written.

```
var window = {
  kittens: ['milo', 'otis', 'garfield']
}
```
Thinking he had to define it as a window object. He seemed pretty upset because he never saw the test run and didn't really understand what he was looking for.

Any way to re-evaluate the spec in order to make the first two test viewable upon running the test file?

**Comment by drakeltheryuujin** [comment]
Hi @Enoch2k2,

Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration students might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
