### ISSUE TITLE
Labs do not instruct user to save file before running tests or submitting.

### ISSUE THREAD

**Issue by snyderc** [learn-co-curriculum/javascript-arrays-lab#14]
Labs do not instruct user to save file before running tests or submitting (learn test / learn submit). Since IDE abstracts away the terminal and code editor, it's unclear to new users (and was unclear to me, with a couple CS courses under my belt) why learn test/learn submit were failing. Suggested remedy: Add instruction to first lab to save all files before attempting learn test/learn submit.

**Comment by drakeltheryuujin** [comment]
We have updated the materials and believe your issue to have been resolved.
