### ISSUE TITLE
Cannot find module 'jsdom/lib/old-api'

### ISSUE THREAD

**Issue by mshehi** [learn-co-curriculum/javascript-arrays-lab#20]
I'm on the Javascript arrays lab, and this lesson's tests won't run because a before hook isn't satisfied. Here's a screenshot below of my error message:

![screen shot 2018-06-24 at 8 39 56 pm](https://user-images.githubusercontent.com/15315732/41825482-d2bc95b2-77ee-11e8-99cb-50ca2520241e.png)

Also, since the tests won't run at all the IDE seems to recognize this as all of the tests passing. 

Would appreciate any help with this!

**Comment by drakeltheryuujin** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
