### ISSUE TITLE
Incorrect statement about splice() method

### ISSUE THREAD

**Issue by PeasOfMind** [learn-co-curriculum/javascript-arrays-lab#21]
Fifth paragraph under "WHAT'S WITH ALL THIS DESTRUCTION?" states: 

"Try to use methods like slice(), concat(), or splice() to return a new array when keep the original array intact."

This is incorrect as the MDN documentation notes that splice() does mutate the original array.

**Comment by cnezames** [comment]
I burned an hour on this. I was just about to raise the issue on this as well as the lesson was very misleading.

>"The splice() method changes the contents of an array by removing existing elements and/or adding new elements."

**Comment by kclm** [comment]
I just ran into this as well and found after going my own search that splice does mutate the original array as well. Not sure the etiquette on replying on Github since I have nothing to add, but I hope it gets fixed quickly for others before they run into the issue.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
