### ISSUE TITLE
Grammar issue/typo

### ISSUE THREAD

**Issue by smoralesjr** [learn-co-curriculum/javascript-arrays-lab#23]
<img width="1275" alt="screen shot 2018-09-27 at 9 26 40 am" src="https://user-images.githubusercontent.com/22152576/46149169-b1fdf300-c237-11e8-9692-ec4da9bdd7c7.png">

There's a typo in the lesson. It says "keep" when it should say "keeping." See attached screenshot.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
