### ISSUE TITLE
Inconsistency in documentation and test files in the 'kittens' array lab

### ISSUE THREAD

**Issue by DanielSeehausen** [learn-co-curriculum/javascript-arrays-lab#4]
Test file defines kittens newly before each function automatically, which the README and website both do not agree with. As we are asked to define kittens, this leads to all tests obscurely failing with functions undefined. Possible solution -- alter the readme and website to reflect the divergence in the index-test.js file, or alter the index-test.js file and require the user to define and manage it themselves.

**Comment by MattMCasey** [comment]
This seems to be a broader characteristic of this self-guided course in general. On an earlier test -- I don't remember which -- I spent hours trying to get the tests to pass. I finally asked for help and learned that I was missing a return, but it was not clear from the README or website that this would be necessary.

**Comment by drakeltheryuujin** [comment]
I've added a hint into `index.js` that might help students move past this issue.

Thank you for spotting this issue and providing feedback.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
