### ISSUE TITLE
First test not working properly

### ISSUE THREAD

**Issue by ruraldreams** [learn-co-curriculum/javascript-arrays-lab#7]
When this lesson loads, index.js shows the following and the first test passes.
`const app = "I don't do much."`
If I empty out index.js and save, the first test still passes.

**Comment by drakeltheryuujin** [comment]
Hi @ruraldreams 

Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this
issue. 💙
